server:
  port: 8080

spring:
  profiles:
    active: dev
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  web:
    resources:
      static-locations: classpath:/static/, classpath:/public/, file:./uploads/
      cache:
        cachecontrol:
          max-age: 86400
          cache-public: true

jwt:
  key:
    private-key: classpath:keys/private.pem
    public-key: classpath:keys/public.pem
  expiration: 86400000

file:
  image-upload: uploads/images/
  video-upload: uploads/videos/

logging:
  level:
    root: INFO
    web: TRACE
    org.springframework.data.neo4j: DEBUG
